# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbaf5ccc18d0be734f6682db53698c8a44d3e7320ba1937aad6e56d0d2ed878ed090e5a0e94376a5fac796ac354723982f08d49805705cf3d1f5b9a2bddba3c8

test:
  secret_key_base: f1dc3cb0fb8fa15318c8ef11a14649c30f0c5e4ca094bece7210d6c7ed7708b84443ece821ca046040890ceaa3915ecbc80e5e0bede86ede633460564c29b4b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
